version: "3.8"

services:
  frontend:
    build:
      context: ./forecaster_app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./forecaster_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./forecaster_backend:/app
    environment:
      - DEBUG=True
