# Generated by Django 4.2.16 on 2024-11-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_person_id', models.CharField(max_length=50)),
                ('delivery_person_age', models.PositiveIntegerField()),
                ('delivery_person_ratings', models.FloatField()),
                ('restaurant_latitude', models.FloatField()),
                ('restaurant_longitude', models.FloatField()),
                ('delivery_location_latitude', models.FloatField()),
                ('delivery_location_longitude', models.FloatField()),
                ('order_date', models.DateField()),
                ('time_ordered', models.TimeField(blank=True, null=True)),
                ('time_order_picked', models.TimeField(blank=True, null=True)),
                ('weather_conditions', models.CharField(blank=True, max_length=100, null=True)),
                ('road_traffic_density', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_condition', models.PositiveSmallIntegerField()),
                ('type_of_order', models.CharField(max_length=100)),
                ('type_of_vehicle', models.CharField(max_length=50)),
                ('multiple_deliveries', models.PositiveIntegerField(blank=True, null=True)),
                ('festival', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=100)),
                ('time_taken', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Delivery Records',
                'ordering': ['-order_date'],
            },
        ),
    ]
