# Generated by Django 4.2.16 on 2024-11-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryrecord',
            options={},
        ),
    ]
