# Generated by Django 4.2.16 on 2024-12-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_deliveryrecord_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegressionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('degree', models.IntegerField()),
                ('coefficients', models.JSONField()),
                ('intercept', models.FloatField()),
                ('mean_squared_error', models.FloatField()),
                ('predictions', models.JSONField()),
                ('actuals', models.JSONField()),
            ],
        ),
    ]
