# Generated by Django 4.2.16 on 2024-12-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_regressionresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.IntegerField()),
                ('cluster', models.IntegerField()),
                ('restaurant_latitude', models.FloatField()),
                ('restaurant_longitude', models.FloatField()),
                ('distance_from_centroid', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
