# Generated by Django 4.2.16 on 2024-12-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_clusteringresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clusteringresult',
            old_name='restaurant_latitude',
            new_name='delivery_location_latitude',
        ),
        migrations.RenameField(
            model_name='clusteringresult',
            old_name='restaurant_longitude',
            new_name='delivery_location_longitude',
        ),
    ]
